filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
        - 'Examples/*'
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 5.6
    dependencies:
        before:
            - sudo composer self-update && composer --version    
    tests:
        override:
            -
                idle_timeout: 5000
                command: 'php -d memory_limit=2048M -f ./vendor/bin/phpunit -- --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'php-clover'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
