filter:
    excluded_paths:
        - 'tests/*'

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 5.6
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'php-clover'
