<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\Banka;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-10 at 12:31:59.
 */
class BankaTest extends FlexiBeeRWTest
{
    /**
     * @var Banka
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Banka;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * Gives You data able to insert into current evidence
     *
     * @param string $code custom record code
     *
     * @return array
     */
    public function getDataForInsert($code = 'UnitTest')
    {
        $dataForInsert               = parent::getDataForInsert($code);
        $loader                      = new \FlexiPeeHP\FlexiBeeRO(null,
            ['evidence' => 'bankovni-ucet']);
        $bankCodeRaw                 = $loader->getColumnsFromFlexibee([
            'kod'], ['limit' => 1]);
        $dataForInsert['banka']      = \FlexiPeeHP\FlexiBeeRO::code($bankCodeRaw[0]['kod']);
        $dataForInsert['typPohybuK'] = 'typPohybu.prijem';
        return $dataForInsert;
    }

    /**
     * @covers FlexiPeeHP\Banka::stahnoutVypisyOnline
     */
    public function testStahnoutVypisyOnline()
    {
        $this->assertInternalType('boolean',
            $this->object->stahnoutVypisyOnline());
    }

    /**
     * @covers FlexiPeeHP\Banka::automatickeParovani
     */
    public function testAutomatickeParovani()
    {
        $this->assertInternalType('boolean',
            $this->object->automatickeParovani());
    }
}
