<?php

namespace Test\FlexiPeeHP;

use \FlexiPeeHP\EvidenceList;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-09-03 at 01:01:15.
 */
class EvidenceListTest extends FlexiBeeROTest
{
    /**
     * @var EvidenceList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new EvidenceList();
    }

    public function checkLists()
    {
        $this->assertTrue(count(EvidenceList::$evidences) > 80);
        $this->assertTrue($this->object->setEvidence('cenik'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
