<?php

namespace Test\FlexiPeeHP;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-09-06 at 15:39:44.
 */
class EvidenceTest extends \Test\Ease\SandTest
{
    /**
     * @var Evidence
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \FlexiPeeHP\Evidence(new \FlexiPeeHP\Adresar(),['limit'=>10]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers FlexiPeeHP\Evidence::__construct
     */
    public function testConstructor()
    {
        $classname = get_class($this->object);
        $mock      = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $mock->__construct(new \FlexiPeeHP\Adresar());
        $this->assertInstanceOf('\FlexiPeeHP\Adresar', $mock->engine);
    }

    /**
     * @covers FlexiPeeHP\Evidence::getEvidenceData
     */
    public function testGetEvidenceData()
    {
        $this->assertIsArray($this->object->GetEvidenceData());
    }

    /**
     * @covers FlexiPeeHP\Evidence::getEvidenceObjects
     */
    public function testGetEvidenceObjects()
    {
        $this->assertInstanceOf('\FlexiPeeHP\Adresar', current( $this->object->GetEvidenceObjects() ) );
    }

    /**
     * @covers FlexiPeeHP\Evidence::getEvidence
     */
    public function testGetEvidence()
    {
        $this->assertEquals('adresar', $this->object->GetEvidence());
    }
}
