<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\PokladniPohyb;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 17:32:11.
 */
class PokladniPohybTest extends FlexiBeeTest
{
    /**
     * @var PokladniPohyb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PokladniPohyb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers FlexiPeeHP\PokladniPohyb::insertToFlexiBee
     * @todo   Implement testInsertToFlexiBee().
     */
    public function testInsertToFlexiBee()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\PokladniPohyb::htmlizeRow
     * @todo   Implement testHtmlizeRow().
     */
    public function testHtmlizeRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}