<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\Searcher;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 17:32:10.
 */
class SearcherTest extends FlexiBeeTest
{
    /**
     * @var Searcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Searcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers FlexiPeeHP\Searcher::registerClass
     * @todo   Implement testRegisterClass().
     */
    public function testRegisterClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Searcher::searchAll
     * @todo   Implement testSearchAll().
     */
    public function testSearchAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}