<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\Stitek;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 17:32:11.
 */
class StitekTest extends FlexiBeeRWTest
{
    /**
     * @var Stitek
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Stitek;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers FlexiPeeHP\Stitek::getLabels
     * @todo   Implement testGetLabels().
     */
    public function testGetLabels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Stitek::listToArray
     * @todo   Implement testListToArray().
     */
    public function testListToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Stitek::getAvailbleLabels
     */
    public function testGetAvailbleLabels()
    {
        $labels = \FlexiPeeHP\Stitek::getAvailbleLabels(new \FlexiPeeHP\FakturaVydana());
        $this->assertTrue(is_array($labels) && count($labels));
    }

    /**
     * @covers FlexiPeeHP\Stitek::setLabel
     * @todo   Implement testSetLabel().
     */
    public function testSetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Stitek::unsetLabel
     * @todo   Implement testUnsetLabel().
     */
    public function testUnsetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
