<?php

namespace Test\FlexiPeeHP;

use PHPUnit\Framework\TestCase;
use PHPUnit_Framework_MockObject_MockObject;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-10 at 12:31:59.
 */
class StitkyTest extends TestCase
{

    protected function setUp()
    {
        $this->calculatorTraitMock = $this->getMockForTrait(\FlexiPeeHP\Banka::class);
    }

    protected function tearDown()
    {
        $this->calculatorTraitMock = null;
    }

    public function testGetLabels()
    {
        $this->calculatorTraitMock->setDataValue('stitky', 'LABELA,LABELB');
        $this->assertEquals(['LABELA' => 'LABELA', 'LABELB' => 'LABELB'],
            $this->calculatorTraitMock->getLabels());
    }
}
