<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\UcetniObdobi;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 17:32:10.
 */
class UcetniObdobiTest extends FlexiBeeTest
{
    /**
     * @var UcetniObdobi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UcetniObdobi;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers FlexiPeeHP\UcetniObdobi::createYearsFrom
     * @todo   Implement testCreateYearsFrom().
     */
    public function testCreateYearsFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}